
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 05 07:14:58 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 3;
  public static final int LINEA = 4;
  public static final int EOF = 0;
}

